---
last_check:
  etag: '"2df3424787afbe972c87719e151b5541"'
  version: 1.6.13
  at: 1402909223
endpoints:
  https://api.travis-ci.org/:
    access_token: t4QqnwzKOSxgJIx8yiuwMw
  https://api.travis-ci.com/:
    access_token: xHCQKRK7CDxu8tgvF3lD7A
repos:
  murphyslaw/infopark_kickstarter:
    endpoint: https://api.travis-ci.org/
  infopark/infopark_kickstarter:
    endpoint: https://api.travis-ci.org/
checked_completion: true
completion_version: 1.6.13
